#!/usr/bin/env php
<?php
use ntentan\Ntentan;
require __DIR__ . '/vendor/PHPMailer/PHPMailerAutoload.php';

// @todo Allow the timezone to be set during installation
date_default_timezone_set('Africa/Accra');

// Tell PHP to stop barking
error_reporting(E_ALL ^ E_NOTICE);

// Ensure that only a single instance of the cron runs at any time
$lockFile = sys_get_temp_dir() . "/kakalika-cron.lock";
if(file_exists($lockFile)){
    fputs(STDERR, "Lock file $lockFile found. Exiting ...\n");
    die();
}
touch($lockFile);

// Load configurations
$ntentan = parse_ini_file(__DIR__ . '/config/ntentan.ini', true);
$ntentan['home'] = __DIR__ . "/ntentan";
$app = parse_ini_file(__DIR__ . "/config/app.ini", true);
$app['home'] = __DIR__;

require "{$ntentan['home']}/lib/Ntentan.php";


Ntentan::$configPath = __DIR__ . "/config/";
Ntentan::setup($ntentan, $app);
\ntentan\views\template_engines\TemplateEngine::prependPath(__DIR__ . '/views/emails');
$emailSettings = \kakalika\modules\projects\email_settings\EmailSettings::getAll();

foreach($emailSettings->toArray() as $settings)
{
    if($settings['project']['email_integration'] != '1'){
        echo "Skipping emails for {$settings['project']['name']}\n";
        continue;
    }
    
    // Check for incoming mails
    echo "Processing emails for {$settings['project']['name']}\n";
    echo "Connecting to {$settings['incoming_server_type']}://{$settings['incoming_server_host']}:{$settings['incoming_server_port']} ... ";
    
    $ssl = $settings['incoming_server_ssl'] == '1' ? "/ssl/novalidate-cert" : "";
    $imap = imap_open(
        "{{$settings['incoming_server_host']}:{$settings['incoming_server_port']}/{$settings['incoming_server_type']}$ssl}INBOX",
        $settings['incoming_server_username'], $settings['incoming_server_password']
    );
    
    if($imap !== false)
    {
        echo "OK\n";
        $messages = imap_search($imap, 'UNSEEN');
        if($messages)
        {
            echo "Processing " . count($messages) . " new mail(s).\n";
            
            foreach($messages as $message)
            {
                $decodedMessage = new \kakalika\lib\EmailDecoder($imap, $message);
                $user = \kakalika\modules\users\Users::getJustFirstWithEmail($decodedMessage->getFromAddress());   
                
                if($user->count() == 0)
                {
                    $user = \kakalika\modules\users\Users::getNew();
                    $user->firstname = $decodedMessage->getSenderName();
                    $user->email = $decodedMessage->getFromAddress();
                    $user->username = $decodedMessage->getFromAddress();
                    $user->password = uniqid();
                    $id = $user->save();
                    $user->id = $id;
                    
                }
                
                $_SESSION['user'] = $user->toArray();
                $to = $decodedMessage->getToAddress();
                
                if(preg_match("/^[_a-z0-9-]+(\.[_a-z0-9-]+)*(\+){1}(?<issue_number>[_a-z0-9-]+)/i", $to, $matches))
                {
                    $issue = kakalika\modules\issues\Issues::getJustFirstWithNumber($matches['issue_number']);
                    $issue->updater = $user->id;
                    $issue->comment = $decodedMessage->getPlainText();
                    foreach($decodedMessage->getAttachments() as $attachment)
                    {
                        $issue->addAttachment($attachment);
                    }
                    $issue->update();
                }
                else
                {
                    $issue = kakalika\modules\issues\Issues::getNew();
                    $issue->title = $decodedMessage->getSubject();
                    $issue->opener = $user->id;
                    $issue->created = $decodedMessage->getTimestamp();
                    $issue->description = $decodedMessage->getPlainText();
                    $issue->project_id = $settings['project']['id'];
                    foreach($decodedMessage->getAttachments() as $attachment)
                    {
                        $issue->addAttachment($attachment);
                    }
                    $issue->save();
                }
            }
        }
        imap_close($imap);
    }
    else 
    {
        echo "FAILED\n";
    }
        
    // Send outgoing mails
    $outgoingMails = \kakalika\modules\outgoing_mails\OutgoingMails::getJustAllWithProjectId($settings['project']['id']);
    foreach($outgoingMails as $outgoingMail)
    {
        $sender = unserialize($outgoingMail->object);
        $sender->send($settings);
        $outgoingMail->delete();
    }
}

unlink($lockFile);
