<?php
/**
 * Generated by yentu on 2nd February, 2015 09:16:58
 */
$app = parse_ini_file('config/app.ini');
$db = parse_ini_file('config/db.ini', true);

$config = array(
    'driver' => $db[$app['context']]['datastore'],
    'host' => $db[$app['context']]['host'],
    'port' => $db[$app['context']]['port'],
    'dbname' => $db[$app['context']]['name'],
    'user' => $db[$app['context']]['user'],
    'password' => $db[$app['context']]['password'],
    'file' => $db[$app['context']]['file']
);