<?php
/**
 * Generated by yentu on 8th November, 2015 09:34:58
 */

begin()
    ->table('components')
        ->foreignKey('project_id')
            ->name('fk_components_1')
            ->onDelete('CASCADE')
            ->onUpdate('CASCADE')
        
    ->table('milestones')
        ->foreignKey('project_id')
            ->name('fk_milestones_1')
            ->onDelete('CASCADE')
            ->onUpdate('CASCADE')        
        
    ->table('issues')
        ->foreignKey('project_id')
            ->name('fk_issues_components')
            ->onDelete('CASCADE')
            ->onUpdate('CASCADE')  
        
    ->table('updates')
        ->foreignKey('issue_id')
            ->name('fk_activities_1')
            ->onDelete('CASCADE')
            ->onUpdate('CASCADE')       
        
    ->table('watchers')
        ->foreignKey('issue_id')
            ->name('fk_watchers_2')
            ->onDelete('CASCADE')
            ->onUpdate('CASCADE')          
        
    ->table('issues')
        ->foreignKey('project_id')
            ->name('fk_issues_projects')
            ->onDelete('CASCADE')
            ->onUpdate('CASCADE')      
        
    ->table('projects_users')
        ->foreignKey('project_id')
            ->name('fk_user_projects_projects')
            ->onDelete('CASCADE')
            ->onUpdate('CASCADE')         
        
->end();

