<?php
/**
 * Generated by yentu on 1st April, 2015 14:44:07
 */

$this->table('components')
    ->column('description')->type('text')->nulls(true)
    ->column('id')->type('integer')->nulls(false)
    ->column('name')->type('string')->nulls(false)->length(255)
    ->column('project_id')->type('integer')->nulls(false)
    ->primaryKey('id')
    ->autoIncrement()
    ->unique('name')->name('name_UNIQUE')
    ->index('project_id')->name('')
    ;

$this->table('issues')
    ->column('assigned')->type('timestamp')->nulls(true)
    ->column('assignee')->type('integer')->nulls(true)
    ->column('component_id')->type('integer')->nulls(true)
    ->column('created')->type('timestamp')->nulls(true)
    ->column('description')->type('text')->nulls(true)
    ->column('id')->type('integer')->nulls(false)
    ->column('kind')->type('string')->nulls(true)->length(45)
    ->column('milestone_id')->type('integer')->nulls(true)
    ->column('number')->type('integer')->nulls(false)
    ->column('number_of_updates')->type('integer')->nulls(true)
    ->column('opener')->type('integer')->nulls(false)
    ->column('priority')->type('string')->nulls(true)->length(45)
    ->column('project_id')->type('integer')->nulls(false)
    ->column('status')->type('string')->nulls(false)->length(45)
    ->column('title')->type('string')->nulls(false)->length(255)
    ->column('updated')->type('timestamp')->nulls(true)
    ->column('updater')->type('integer')->nulls(true)
    ->primaryKey('id')
    ->autoIncrement()
    ->index('project_id','assignee','opener','updater','component_id','milestone_id','title')->name('')
    ;

$this->table('issue_attachments')
    ->column('attachment_file')->type('string')->nulls(false)->length(255)
    ->column('created')->type('timestamp')->nulls(true)
    ->column('id')->type('integer')->nulls(false)
    ->column('issue_id')->type('integer')->nulls(false)
    ->column('name')->type('string')->nulls(false)->length(255)
    ->column('size')->type('text')->nulls(true)->length(16777215)
    ->column('type')->type('string')->nulls(true)->length(45)
    ->column('update_id')->type('integer')->nulls(true)
    ->column('user_id')->type('integer')->nulls(false)
    ->primaryKey('id')
    ->autoIncrement()
    ->unique('attachment_file')->name('attachment_file_UNIQUE')
    ->index('issue_id','user_id')->name('')
    ;

$this->table('milestones')
    ->column('description')->type('text')->nulls(true)
    ->column('due_date')->type('date')->nulls(true)
    ->column('id')->type('integer')->nulls(false)
    ->column('name')->type('string')->nulls(false)->length(255)
    ->column('project_id')->type('integer')->nulls(false)
    ->primaryKey('id')
    ->autoIncrement()
    ->index('project_id')->name('')
    ;

$this->table('outgoing_mails')
    ->column('id')->type('integer')->nulls(false)
    ->column('object')->type('text')->nulls(false)
    ->column('project_id')->type('integer')->nulls(false)
    ->primaryKey('id')
    ->autoIncrement()
    ->index('project_id')->name('')
    ;

$this->table('projects')
    ->column('code')->type('string')->nulls(false)->length(45)
    ->column('description')->type('text')->nulls(true)
    ->column('email_integration')->type('boolean')->nulls(true)
    ->column('id')->type('integer')->nulls(false)
    ->column('name')->type('string')->nulls(false)->length(255)
    ->column('number_of_issues')->type('integer')->nulls(true)->defaultValue("0")
    ->primaryKey('id')
    ->autoIncrement()
    ->unique('code')->name('code_UNIQUE')
    ;

$this->table('projects_email_settings')
    ->column('email_address')->type('string')->nulls(true)->length(255)
    ->column('email_display_name')->type('string')->nulls(true)->length(255)
    ->column('id')->type('integer')->nulls(false)
    ->column('incoming_server_host')->type('string')->nulls(true)->length(255)
    ->column('incoming_server_password')->type('string')->nulls(true)->length(45)
    ->column('incoming_server_port')->type('integer')->nulls(true)
    ->column('incoming_server_ssl')->type('boolean')->nulls(true)
    ->column('incoming_server_type')->type('string')->nulls(true)->length(45)
    ->column('incoming_server_username')->type('string')->nulls(true)->length(45)
    ->column('outgoing_server_authentication')->type('boolean')->nulls(true)
    ->column('outgoing_server_encryption')->type('string')->nulls(true)->length(45)
    ->column('outgoing_server_host')->type('string')->nulls(true)->length(255)
    ->column('outgoing_server_password')->type('string')->nulls(true)->length(45)
    ->column('outgoing_server_port')->type('integer')->nulls(true)
    ->column('outgoing_server_username')->type('string')->nulls(true)->length(45)
    ->column('project_id')->type('integer')->nulls(false)
    ->primaryKey('id')
    ->autoIncrement()
    ->index('project_id')->name('')
    ;

$this->table('updates')
    ->column('assignee')->type('integer')->nulls(true)
    ->column('comment')->type('text')->nulls(true)
    ->column('component_id')->type('integer')->nulls(true)
    ->column('created')->type('timestamp')->nulls(false)
    ->column('id')->type('integer')->nulls(false)
    ->column('issue_id')->type('integer')->nulls(false)
    ->column('kind')->type('string')->nulls(true)->length(45)
    ->column('milestone_id')->type('integer')->nulls(true)
    ->column('number')->type('integer')->nulls(false)
    ->column('priority')->type('string')->nulls(true)->length(45)
    ->column('status')->type('string')->nulls(true)->length(45)
    ->column('title')->type('string')->nulls(true)->length(255)
    ->column('user_id')->type('integer')->nulls(false)
    ->primaryKey('id')
    ->autoIncrement()
    ->index('issue_id','user_id')->name('')
    ;

$this->table('users')
    ->column('blocked')->type('boolean')->nulls(true)
    ->column('email')->type('string')->nulls(false)->length(45)
    ->column('firstname')->type('string')->nulls(false)->length(45)
    ->column('id')->type('integer')->nulls(false)
    ->column('is_admin')->type('boolean')->nulls(true)
    ->column('lastname')->type('string')->nulls(true)->length(45)
    ->column('password')->type('string')->nulls(false)->length(45)
    ->column('username')->type('string')->nulls(false)->length(45)
    ->primaryKey('id')
    ->autoIncrement()
    ->unique('email')->name('email_UNIQUE')
    ->unique('username')->name('username_UNIQUE')
    ;

$this->table('user_projects')
    ->column('admin')->type('boolean')->nulls(true)
    ->column('creator')->type('boolean')->nulls(true)
    ->column('id')->type('integer')->nulls(false)
    ->column('project_id')->type('integer')->nulls(false)
    ->column('user_id')->type('integer')->nulls(false)
    ->primaryKey('id')
    ->autoIncrement()
    ->index('project_id','user_id')->name('')
    ;

$this->table('watchers')
    ->column('id')->type('integer')->nulls(false)
    ->column('issue_id')->type('integer')->nulls(true)
    ->column('user_id')->type('integer')->nulls(true)
    ->primaryKey('id')
    ->autoIncrement()
    ->index('user_id','issue_id')->name('')
    ;

$this->table('components')
    ->foreignKey('project_id')
    ->references($this->reftable('projects'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_components_1');

$this->table('issues')
    ->foreignKey('component_id')
    ->references($this->reftable('components'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issues_components');

$this->table('issues')
    ->foreignKey('milestone_id')
    ->references($this->reftable('milestones'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issues_milestones');

$this->table('issues')
    ->foreignKey('project_id')
    ->references($this->reftable('projects'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issues_projects');

$this->table('issues')
    ->foreignKey('assignee')
    ->references($this->reftable('users'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issues_users_assignee');

$this->table('issues')
    ->foreignKey('opener')
    ->references($this->reftable('users'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issues_users_opener');

$this->table('issues')
    ->foreignKey('updater')
    ->references($this->reftable('users'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issues_users_updater');

$this->table('issue_attachments')
    ->foreignKey('issue_id')
    ->references($this->reftable('issues'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issue_attachments_1');

$this->table('issue_attachments')
    ->foreignKey('user_id')
    ->references($this->reftable('users'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_issue_attachments_2');

$this->table('milestones')
    ->foreignKey('project_id')
    ->references($this->reftable('projects'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_milestones_1');

$this->table('outgoing_mails')
    ->foreignKey('project_id')
    ->references($this->reftable('projects'))
    ->columns('id')
    ->onDelete('CASCADE')
    ->onUpdate('CASCADE')
    ->name('fk_outgoing_mails_1');

$this->table('projects_email_settings')
    ->foreignKey('project_id')
    ->references($this->reftable('projects'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_email_integration_settings_1');

$this->table('updates')
    ->foreignKey('issue_id')
    ->references($this->reftable('issues'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_activities_1');

$this->table('updates')
    ->foreignKey('user_id')
    ->references($this->reftable('users'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_activities_2');

$this->table('user_projects')
    ->foreignKey('project_id')
    ->references($this->reftable('projects'))
    ->columns('id')
    ->onDelete('CASCADE')
    ->onUpdate('CASCADE')
    ->name('fk_user_projects_projects');

$this->table('user_projects')
    ->foreignKey('user_id')
    ->references($this->reftable('users'))
    ->columns('id')
    ->onDelete('CASCADE')
    ->onUpdate('CASCADE')
    ->name('fk_user_projects_users');

$this->table('watchers')
    ->foreignKey('user_id')
    ->references($this->reftable('users'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_watchers_1');

$this->table('watchers')
    ->foreignKey('issue_id')
    ->references($this->reftable('issues'))
    ->columns('id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('fk_watchers_2');

