#!/usr/bin/env php
<?php
error_reporting(E_ALL ^ E_NOTICE);

require __DIR__ . "/../vendor/autoload.php";

anyen\Runner::run(__DIR__ . "/wizards/install.php", array('banner' => 'Kakalika Issue Tracker'));
